[package]
name = "base64"
version = "0.1.0"
authors = ["Alex Forehand <forehand.alex@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "*"
regex = "1"
hex = "*"